DD-272-update-dependencies
HMPO/hmpo-model pull request #66
Opened 2024-10-03 13:12 UTC by KLV96

Drop Node 14, 16 and 18 and allowing only 20.x || 22.x and updating the following dependencies: 
debug ^4.3.6 -> ^4.3.7
eslint ^8.57.0 -> ^9.12.0 and replacing .eslintrc with eslint.config.js 
hmpo-logger ^7.0.2 -> ***
mocha ^10.7.0 -> ^10.7.3
nyc ^17.0.0 -> ^17.1.0
proxyquire ^2.0.0 -> ^2.1.3
sinon ^18.0.0 -> ^19.0.2
Adding Husky ^9.1.6 then adding ./husky/pre-push
globals ^15.9.0
http-proxy-agent ^5.0.0 -> ^7.0.2
https-proxy-agent ^5.0.1 -> ^7.0.5

2024-10-07 10:43 UTC, SamChatfield requested changes

2024-10-07 10:43 UTC, SamChatfield commented on package.json
>      "https-proxy-agent": "^5.0.1",
There's 7.x versions available for both of these now which we should upgrade to if we can

2024-10-07 10:43 UTC, SamChatfield commented on package.json
> +    "eslint": "^9.11.1",
Version 9.12.0 now available that we can go to

2024-10-09 17:14 UTC, SamChatfield requested changes

2024-10-09 17:14 UTC, SamChatfield commented on lib/remote-model.js
> +            const { HttpProxyAgent } = require('http-proxy-agent');
The proxy agent constructors here don't seem to match the changed API introduced in 6.0.0 so calls through a proxy are most likely broken. Tests might not be working properly if they're passing on this.

https://github.com/TooTallNate/proxy-agents/blob/main/packages/https-proxy-agent/CHANGELOG.md#600
https://github.com/TooTallNate/proxy-agents/blob/main/packages/http-proxy-agent/CHANGELOG.md#600

2024-10-09 17:45 UTC, SamChatfield requested changes

2024-10-09 17:45 UTC, SamChatfield commented on .eslintrc
`test/.eslintrc` also needs removing

2024-10-17 14:04 UTC, cmcgee480 approved these changes

2024-10-17 14:45 UTC, SamChatfield approved these changes
LGTM

2024-10-17 14:52 UTC, imran-gov approved these changes

2024-10-20 21:06 UTC, merged